# Generated by Django 2.1.5 on 2019-01-25 22:46

from django.db import migrations, models
import django.contrib.postgres.fields.jsonb


class Migration(migrations.Migration):

    dependencies = [("api_v2", "0027_auto_20200519_2019")]

    operations = [
        migrations.AddField(
            model_name="credentialtype",
            name="credential_title",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="credentialtype",
            name="highlighted_attributes",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        )
    ]
