# Generated by Django 2.2.28 on 2024-08-22 21:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0030_remove_credentialtype_schema_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='raw_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
