# Generated by Django 2.2.28 on 2024-08-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0032_remove_credentialtype_visible_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialtype',
            name='format',
            field=models.CharField(blank=True, choices=[('VC_DI', 'vc_di'), ('ANONCREDS', 'anoncreds')], max_length=255, null=True),
        ),
    ]
