# Generated by Django 2.2.28 on 2024-08-26 15:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0033_credentialtype_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialtype',
            name='raw_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
