# Generated by Django 2.2.28 on 2024-08-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0034_credentialtype_raw_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='format',
            field=models.CharField(blank=True, choices=[('VC_DI', 'vc_di'), ('ANONCREDS', 'anoncreds')], max_length=255, null=True),
        ),
    ]
