# For details on how this file works refer to:
#  - https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  #  - Check for updates once a week
  #  - Group all updates into a single PR
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-actions:
        patterns: [ "*" ]

  # Maintain dependencies for Python Packages
  - package-ecosystem: "pip"
    directory: "/echo-service"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Maintain dependencies for Python Packages
  - package-ecosystem: "pip"
    directory: "/server/vcr-server"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Maintain dependencies for Python Packages
  - package-ecosystem: "pip"
    directory: "/server/message_families/issuer_registration"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Maintain dependencies for docker images inside manifests
  - package-ecosystem: "docker"
    directory: "/docker/db"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"
    
  # Maintain dependencies for docker images inside manifests
  - package-ecosystem: "docker"
    directory: "/docker/echo-service"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker images inside manifests
  - package-ecosystem: "docker"
    directory: "/docker/utils"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"

  # Maintain dependencies for docker images inside manifests
  - package-ecosystem: "docker"
    directory: "/docker/vcr-agent"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Canada/Pacific"