# Generated by Django 2.2.8 on 2020-01-07 18:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icat_hooks', '0005_auto_20191218_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialHookStats',
            fields=[
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('worker_id', models.TextField(max_length=64, primary_key=True, serialize=False)),
                ('total_count', models.IntegerField(default=0)),
                ('attempt_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('fail_count', models.IntegerField(default=0)),
                ('retry_count', models.IntegerField(default=0)),
                ('retry_fail_count', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
