# Generated by Django 2.1.7 on 2019-04-02 15:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0024_auto_20190328_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='HookableCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('corp_num', models.TextField(null=True)),
                ('credential_type', models.TextField(null=True)),
                ('credential_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hookable_cred',
                'ordering': ('corp_num', 'credential_type'),
            },
        ),
        migrations.AlterField(
            model_name='subscription',
            name='credential_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credential_subscription', to='api_v2.CredentialType'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='source_id',
            field=models.TextField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='hookablecredential',
            unique_together={('corp_num', 'credential_type')},
        ),
    ]
