# Generated by Django 2.1.7 on 2019-04-02 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_hooks', '0001_initial'),
        ('api_v2', '0025_auto_20190402_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='hook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credential_subscription', to='rest_hooks.Hook'),
        ),
    ]
