# Generated by Django 2.1.7 on 2019-04-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0028_auto_20190402_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='hookablecredential',
            name='topic_status',
            field=models.TextField(default='New'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='hookablecredential',
            unique_together=set(),
        ),
    ]
