# Generated by Django 2.2.3 on 2019-07-29 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0024_merge_20190201_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credential',
            old_name='wallet_id',
            new_name='credential_exchange_id',
        ),
        migrations.AlterField(
            model_name='topicrelationship',
            name='related_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_rels', to='api_v2.Topic'),
        ),
        migrations.AlterField(
            model_name='topicrelationship',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_rels', to='api_v2.Topic'),
        ),
    ]
