# Generated by Django 2.2.5 on 2019-09-23 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0025_auto_20190729_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credential',
            old_name='credential_exchange_id',
            new_name='credential_id',
        ),
    ]
