version: 2
jobs:
  build:
    steps:
      # - checkout
      - run: 
          name: Run Tests
          command: |
             scripts/run_tests
      # - run: 
      #     name: Push to Codecov.io (Optional Step)
      #     command: |
      #         cp ~/tests/apex/test-result-codecoverage.json .
      #         bash <(curl -s https://codecov.io/bash)
      # - run: 
      #     name: Clean Up
      #     when: always
      #     command: |
      #         node_modules/sfdx-cli/bin/run force:org:delete -u scratch -p
      #         rm ~/tests/apex/*.txt ~/tests/apex/test-result-7*.json