FROM aries-agent

RUN echo 1

RUN pip3 install --no-cache-dir -e "git+https://github.com/ianco/indy-catalyst.git@refactoring#egg=subdir&subdirectory=credential-registry/message_families/issuer_registration"
