name: Build Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  packages: write
  contents: write

jobs:
  build_vcr_agent:
    name: 'Build Traction Aca-Py'
    runs-on: ubuntu-latest
    if: github.repository_owner == 'bcgov'
    steps:
      - uses: actions/checkout@v4    

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare docker tags for image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/aries-vcr-agent
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=ref
            type=sha

      - name: Build and push image
        id: builder
        uses: docker/build-push-action@v6
        with:
          context: ./docker/vcr-agent
          file: ./docker/vcr-agent/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
